name: "ArgoCD Build & Validate Manifests"
description: "Build Kubernetes manifests from ArgoCD application definitions and validate them using kubeconform"
author: "Nasus20202"
inputs:
  manifests-dir:
    description: "Directory to output generated manifests"
    required: false
    default: "manifests"
  apps-dir:
    description: "Directory containing ArgoCD application manifests"
    required: true
    default: ""
  base-path:
    description: "Base path for resolving relative paths in ArgoCD apps"
    required: true
    default: ""
  skip-files:
    description: "Comma-separated list of files to skip"
    required: false
    default: ""
  skip-resources:
    description: "Comma-separated list of Kubernetes resources to skip during validation"
    required: false
    default: "CustomResourceDefinition"
  state-dir:
    description: "Directory for storing manifest state for diff comparison. If empty or non-existent, it will be initialized with current manifests."
    required: false
    default: ""
  comment-on-pr:
    description: "Whether to post manifest diff as a PR comment (requires state-dir to be set)"
    required: false
    default: "false"
  github-token:
    description: "GitHub token for posting PR comments (defaults to github.token)"
    required: false
    default: ""
  commit-state:
    description: "Whether to commit the state directory back to the repository after comparison (e.g. after merging a PR). Requires github-token with write permissions."
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4

    - name: Run build manifests script
      shell: bash
      run: |
        bash "${{ github.action_path }}/build-manifests.sh" "${{ inputs.manifests-dir }}" "${{ inputs.apps-dir }}" "${{ inputs.base-path }}" "${{ inputs.skip-files }}"

    - name: Validate Kubernetes manifests
      shell: bash
      run: |
        # Build kubeconform arguments
        args="-summary -output text -schema-location default -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json"
        if [ -n "${{ inputs.skip-resources }}" ]; then
          args="$args -skip ${{ inputs.skip-resources }}"
        fi

        # Convert manifests directory to absolute path for Docker volume mount
        if [ ! -d "${{ inputs.manifests-dir }}" ]; then
          echo "Error: Manifests directory '${{ inputs.manifests-dir }}' does not exist."
          exit 1
        fi
        manifests_abs_path=$(cd "${{ inputs.manifests-dir }}" && pwd)

        # Run kubeconform via Docker
        set +e
        echo "Running kubeconform via Docker on: $manifests_abs_path"
        output=$(docker run --rm -v "$manifests_abs_path:/manifests:ro" ghcr.io/yannh/kubeconform:v0.7.0 $args /manifests)
        exit_code=$?
        set -e

        echo "## Kubeconform Validation Results" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "$output" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

        if [ $exit_code -ne 0 ]; then
          echo "Kubeconform validation failed."
          exit $exit_code
        else
          echo "Kubeconform validation succeeded."
        fi

    - name: Compare manifests with state
      id: compare
      if: ${{ inputs.state-dir != '' }}
      shell: bash
      run: |
        bash "${{ github.action_path }}/compare-manifests.sh" "${{ inputs.state-dir }}" "${{ inputs.manifests-dir }}"

    - name: Post PR comment
      if: ${{ inputs.state-dir != '' && inputs.comment-on-pr == 'true' && (steps.compare.outputs.DIFF_STATUS == 'changed' || steps.compare.outputs.DIFF_STATUS == 'unchanged') && github.event_name == 'pull_request' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        if [ -z "$GH_TOKEN" ]; then
          echo "Warning: github-token is not set. Skipping PR comment."
          exit 0
        fi

        PR_NUMBER="${{ github.event.pull_request.number }}"
        if [ -z "$PR_NUMBER" ]; then
          echo "Not in a pull request context. Skipping PR comment."
          exit 0
        fi

        REPO="${{ github.repository }}"
        STATUS="${{ steps.compare.outputs.DIFF_STATUS }}"

        if [ "$STATUS" = "changed" ]; then
          COMMENT_FILE="${{ steps.compare.outputs.DIFF_COMMENT_FILE }}"
          if [ -z "$COMMENT_FILE" ] || [ ! -f "$COMMENT_FILE" ]; then
            echo "No diff comment file found. Skipping PR comment."
            exit 0
          fi
          COMMENT_BODY=$(cat "$COMMENT_FILE")
        else
          COMMENT_BODY="## ArgoCD Manifest Changes

        No changes detected in manifests."
        fi

        # Check for existing comment to update
        EXISTING_COMMENT_ID=$(curl -sf -H "Authorization: token $GH_TOKEN" \
          "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments?per_page=100" | \
          jq -r '.[] | select(.body | startswith("## ArgoCD Manifest Changes")) | .id' | head -1) || {
          echo "Warning: Failed to fetch existing PR comments."
          EXISTING_COMMENT_ID=""
        }

        if [ -n "$EXISTING_COMMENT_ID" ] && [ "$EXISTING_COMMENT_ID" != "null" ]; then
          echo "Updating existing PR comment $EXISTING_COMMENT_ID..."
          curl -sf -X PATCH \
            -H "Authorization: token $GH_TOKEN" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/$REPO/issues/comments/$EXISTING_COMMENT_ID" \
            -d "$(jq -n --arg body "$COMMENT_BODY" '{body: $body}')" > /dev/null || {
            echo "Warning: Failed to update PR comment."
            exit 0
          }
        else
          echo "Creating new PR comment..."
          curl -sf -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments" \
            -d "$(jq -n --arg body "$COMMENT_BODY" '{body: $body}')" > /dev/null || {
            echo "Warning: Failed to create PR comment."
            exit 0
          }
        fi

        echo "PR comment posted successfully."

    - name: Add diff to job summary
      if: ${{ inputs.state-dir != '' && steps.compare.outputs.DIFF_STATUS != '' }}
      shell: bash
      run: |
        echo "" >> $GITHUB_STEP_SUMMARY
        STATUS="${{ steps.compare.outputs.DIFF_STATUS }}"
        SUMMARY="${{ steps.compare.outputs.DIFF_SUMMARY }}"

        if [ "$STATUS" = "changed" ]; then
          COMMENT_FILE="${{ steps.compare.outputs.DIFF_COMMENT_FILE }}"
          if [ -n "$COMMENT_FILE" ] && [ -f "$COMMENT_FILE" ]; then
            cat "$COMMENT_FILE" >> $GITHUB_STEP_SUMMARY
          fi
        elif [ "$STATUS" = "initialized" ]; then
          echo "## ArgoCD Manifest State" >> $GITHUB_STEP_SUMMARY
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
        else
          echo "## ArgoCD Manifest Changes" >> $GITHUB_STEP_SUMMARY
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Commit state to repository
      if: ${{ inputs.state-dir != '' && inputs.commit-state == 'true' && steps.compare.outputs.DIFF_STATUS != '' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        if [ -z "$GH_TOKEN" ]; then
          echo "Warning: github-token is not set. Skipping state commit."
          exit 0
        fi

        STATE_DIR="${{ inputs.state-dir }}"
        STATUS="${{ steps.compare.outputs.DIFF_STATUS }}"

        if [ ! -d "$STATE_DIR" ]; then
          echo "State directory does not exist. Skipping commit."
          exit 0
        fi

        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add "$STATE_DIR"

        if git diff --cached --quiet; then
          echo "No changes to commit in state directory."
          exit 0
        fi

        if [ "$STATUS" = "initialized" ]; then
          git commit -m "chore: initialize ArgoCD manifest state"
        else
          git commit -m "chore: update ArgoCD manifest state"
        fi

        git push || {
          echo "Error: Failed to push state changes. Ensure the github-token has write permissions and the workflow has 'contents: write' permission."
          exit 1
        }
        echo "State committed and pushed to repository."
