name: "ArgoCD Build & Validate Manifests"
description: "Build Kubernetes manifests from ArgoCD application definitions and validate them using kubeconform"
author: "Nasus20202"
inputs:
  manifests-dir:
    description: "Directory to output generated manifests"
    required: false
    default: "manifests"
  apps-dir:
    description: "Directory containing ArgoCD application manifests"
    required: true
    default: ""
  skip-files:
    description: "Comma-separated list of files to skip"
    required: false
    default: ""
  skip-resources:
    description: "Comma-separated list of Kubernetes resources to skip during validation"
    required: false
    default: "CustomResourceDefinition"
  state-dir:
    description: "Directory for storing manifest state for diff comparison. If empty or non-existent, it will be initialized with current manifests."
    required: false
    default: ""
  comment-on-pr:
    description: "Whether to post manifest diff as a PR comment (requires state-dir to be set)"
    required: false
    default: "false"
  github-token:
    description: "GitHub token for posting PR comments (defaults to github.token)"
    required: false
    default: ""
  commit-state:
    description: "Whether to commit the state directory back to the repository after comparison (e.g. after merging a PR). Requires github-token with write permissions."
    required: false
    default: "false"
  validate-argo:
    description: "Whether to validate ArgoCD application/applicationset definitions before rendering"
    required: false
    default: "true"
  kube-version:
    description: "Kubernetes version to pass to helm template (e.g. 1.30.0). Auto-detected if not set."
    required: false
    default: ""
  schema-locations:
    description: "Comma-separated additional kubeconform schema locations for CRD validation"
    required: false
    default: ""
  verbose:
    description: "Enable verbose debug output"
    required: false
    default: "false"
outputs:
  diff-status:
    description: "Diff status: 'initialized', 'changed', or 'unchanged'"
    value: ${{ steps.compare.outputs.diff-status }}
  diff-summary:
    description: "One-line summary of changes (e.g. Added/Removed/Modified counts)"
    value: ${{ steps.compare.outputs.diff-summary }}
  diff-comment-file:
    description: "Path to generated PR comment markdown file (set when status is 'changed')"
    value: ${{ steps.compare.outputs.diff-comment-file }}
runs:
  using: "composite"
  steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: "vv1.35.1"

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: "v4.1"

    - name: Set up Kubeconform
      shell: bash
      run: "${{ github.action_path }}/scripts/setup-kubeconform.sh"

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: Set up Python dependencies
      shell: bash
      run: pip install -q -r "${{ github.action_path }}/requirements.txt"

    - name: Build, validate, and compare manifests
      id: compare
      shell: bash
      env:
        INPUT_MANIFESTS-DIR: ${{ inputs.manifests-dir }}
        INPUT_APPS-DIR: ${{ inputs.apps-dir }}
        INPUT_SKIP-FILES: ${{ inputs.skip-files }}
        INPUT_SKIP-RESOURCES: ${{ inputs.skip-resources }}
        INPUT_STATE-DIR: ${{ inputs.state-dir }}
        INPUT_COMMENT-ON-PR: ${{ inputs.comment-on-pr }}
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
        INPUT_COMMIT-STATE: ${{ inputs.commit-state }}
        INPUT_VALIDATE-ARGO: ${{ inputs.validate-argo }}
        INPUT_KUBE-VERSION: ${{ inputs.kube-version }}
        INPUT_SCHEMA-LOCATIONS: ${{ inputs.schema-locations }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
      run: |
        cd "${{ github.workspace }}"
        PYTHONPATH="${{ github.action_path }}" python -m src.main

    - name: Post PR comment
      if: ${{ inputs.state-dir != '' && inputs.comment-on-pr == 'true' && (steps.compare.outputs.diff-status == 'changed' || steps.compare.outputs.diff-status == 'unchanged') && github.event_name == 'pull_request' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        DIFF_STATUS: ${{ steps.compare.outputs.diff-status }}
        DIFF_COMMENT_FILE: ${{ steps.compare.outputs.diff-comment-file }}
      run: "${{ github.action_path }}/scripts/post-pr-comment.sh"

    - name: Add diff to job summary
      if: ${{ inputs.state-dir != '' && steps.compare.outputs.diff-status != '' }}
      shell: bash
      env:
        DIFF_STATUS: ${{ steps.compare.outputs.diff-status }}
        DIFF_SUMMARY: ${{ steps.compare.outputs.diff-summary }}
        DIFF_COMMENT_FILE: ${{ steps.compare.outputs.diff-comment-file }}
      run: "${{ github.action_path }}/scripts/job-summary.sh"

    - name: Commit state to repository
      if: ${{ inputs.state-dir != '' && inputs.commit-state == 'true' && steps.compare.outputs.diff-status != '' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        STATE_DIR: ${{ inputs.state-dir }}
        DIFF_STATUS: ${{ steps.compare.outputs.diff-status }}
      run: "${{ github.action_path }}/scripts/commit-state.sh"
